version: "3.8"

services:
  mongodb-27020:
    image: mongo:latest
    container_name: mongodb-27020
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data_27020:/data/db
    environment:
      - MONGO_INITDB_DATABASE=newbiv2
    restart: always

volumes:
  mongodb_data_27020:
