/**
 * E2E Test Data — MongoDB seed fixtures.
 *
 * All ObjectIds are deterministic so documents can cross-reference each other.
 * Fields match the real Mongoose schemas in newbi-api/src/models/.
 */
import { ObjectId } from "mongodb";

// ─── Fixed ObjectIds ────────────────────────────────────────────────
export const IDS = {
  user: new ObjectId("aaaaaaaaaaaaaaaaaaaaa001"),
  organizationId: new ObjectId("bbbbbbbbbbbbbbbbbbbb0001"),
  memberId: new ObjectId("bbbbbbbbbbbbbbbbbbbb0002"),
  clientAlpha: new ObjectId("cccccccccccccccccccc0001"),
  clientBeta: new ObjectId("cccccccccccccccccccc0002"),
  invoiceDraft: new ObjectId("dddddddddddddddddddd0001"),
  invoicePending: new ObjectId("dddddddddddddddddddd0002"),
  invoicePaid: new ObjectId("dddddddddddddddddddd0003"),
  supplierInvoice: new ObjectId("eeeeeeeeeeeeeeeeeeee0001"),
  quoteDraft: new ObjectId("ffffffffffffffffffff0001"),
  quotePending: new ObjectId("ffffffffffffffffffff0002"),
  quoteCompleted: new ObjectId("ffffffffffffffffffff0003"),
};

// ─── Credentials (used in auth.setup.js & test-data.fixture.js) ─────
export const TEST_CREDENTIALS = {
  email: "test-e2e@newbi.fr",
  password: "TestNewbi2024!",
};

// ─── User ───────────────────────────────────────────────────────────
// Password will be hashed at seed time (bcryptjs, 10 rounds).
export const TEST_USER = {
  _id: IDS.user,
  email: TEST_CREDENTIALS.email,
  password: TEST_CREDENTIALS.password, // plain — hashed by global-setup
  name: "Test E2E",
  emailVerified: true,
  isEmailVerified: true,
  isDisabled: false,
  image: null,
  profile: {
    firstName: "Test",
    lastName: "E2E",
    phone: "+33600000000",
  },
  companyInfo: {
    name: "Newbi Test SASU",
    email: "contact@newbi-test.fr",
    phone: "+33100000000",
    siret: "12345678901234",
    vatNumber: "FR12345678901",
    companyStatus: "SASU",
    capitalSocial: "1000",
    rcs: "Paris",
    transactionCategory: "SERVICES",
    vatPaymentCondition: "ENCAISSEMENTS",
    address: {
      fullName: "Newbi Test SASU",
      street: "1 rue du Test",
      city: "Paris",
      postalCode: "75001",
      country: "France",
    },
    bankDetails: {
      iban: "FR7630006000011234567890189",
      bic: "BNPAFRPP",
      bankName: "BNP Paribas",
    },
  },
  createdAt: new Date(),
  updatedAt: new Date(),
};

// ─── Organization (Better Auth — raw collection) ────────────────────
export const TEST_ORGANIZATION = {
  _id: IDS.organizationId,
  name: "Newbi Test SASU",
  slug: "newbi-test-sasu",
  logo: null,
  metadata: null,
  createdAt: new Date(),
};

// ─── Member (Better Auth — raw collection) ──────────────────────────
export const TEST_MEMBER = {
  _id: IDS.memberId,
  userId: IDS.user.toString(),
  organizationId: IDS.organizationId.toString(),
  role: "owner",
  createdAt: new Date(),
};

// ─── Clients ────────────────────────────────────────────────────────
const now = new Date();

export const TEST_CLIENTS = [
  {
    _id: IDS.clientAlpha,
    name: "Entreprise Alpha SAS",
    email: "contact@alpha-sas.fr",
    phone: "+33612345678",
    type: "COMPANY",
    siret: "98765432100012",
    vatNumber: "FR98765432100",
    isInternational: false,
    isBlocked: false,
    address: {
      fullName: "Entreprise Alpha SAS",
      street: "42 avenue des Champs-Élysées",
      city: "Paris",
      postalCode: "75008",
      country: "France",
    },
    firstName: "Jean",
    lastName: "Dupont",
    contacts: [],
    notes: [],
    customFields: [],
    activityLog: [],
    assignedMembers: [],
    createdBy: IDS.user,
    workspaceId: IDS.organizationId,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: IDS.clientBeta,
    name: "Micro-entreprise Beta",
    email: "beta.micro@gmail.com",
    phone: "+33698765432",
    type: "COMPANY",
    siret: "11223344556677",
    vatNumber: "",
    isInternational: false,
    isBlocked: false,
    address: {
      fullName: "Micro-entreprise Beta",
      street: "7 rue de la Liberté",
      city: "Lyon",
      postalCode: "69001",
      country: "France",
    },
    firstName: "Marie",
    lastName: "Martin",
    contacts: [],
    notes: [],
    customFields: [],
    activityLog: [],
    assignedMembers: [],
    createdBy: IDS.user,
    workspaceId: IDS.organizationId,
    createdAt: now,
    updatedAt: now,
  },
];

// ─── Shared company info snapshot (embedded in invoices) ────────────
const companyInfoSnapshot = {
  name: TEST_USER.companyInfo.name,
  address: TEST_USER.companyInfo.address,
  phone: TEST_USER.companyInfo.phone,
  email: TEST_USER.companyInfo.email,
  siret: TEST_USER.companyInfo.siret,
  vatNumber: TEST_USER.companyInfo.vatNumber,
  capitalSocial: TEST_USER.companyInfo.capitalSocial,
  rcs: TEST_USER.companyInfo.rcs,
  bankDetails: TEST_USER.companyInfo.bankDetails,
  companyStatus: TEST_USER.companyInfo.companyStatus,
  transactionCategory: TEST_USER.companyInfo.transactionCategory,
  vatPaymentCondition: TEST_USER.companyInfo.vatPaymentCondition,
};

// ─── Helper: build client snapshot for invoice ──────────────────────
function clientSnapshot(client: (typeof TEST_CLIENTS)[number]) {
  return {
    _id: client._id,
    name: client.name,
    email: client.email,
    phone: client.phone,
    type: client.type,
    siret: client.siret,
    vatNumber: client.vatNumber,
    address: client.address,
  };
}

// ─── Invoices ───────────────────────────────────────────────────────
const currentYear = now.getFullYear();
const currentMonth = String(now.getMonth() + 1).padStart(2, "0");
const prefix = `F-${currentYear}${currentMonth}`;

export const TEST_INVOICES = [
  // 1. Brouillon (DRAFT)
  {
    _id: IDS.invoiceDraft,
    prefix,
    number: null, // drafts have no number
    issueDate: now,
    dueDate: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000),
    invoiceType: "standard",
    status: "DRAFT",
    client: clientSnapshot(TEST_CLIENTS[0]),
    companyInfo: companyInfoSnapshot,
    items: [
      {
        description: "Développement site vitrine",
        quantity: 1,
        unitPrice: 2500,
        vatRate: 20,
        unit: "forfait",
        discount: 0,
        discountType: "PERCENTAGE",
        progressPercentage: 100,
      },
    ],
    totalHT: 2500,
    totalVAT: 500,
    totalTTC: 3000,
    finalTotalHT: 2500,
    finalTotalVAT: 500,
    finalTotalTTC: 3000,
    discount: 0,
    discountType: "PERCENTAGE",
    showBankDetails: false,
    headerNotes: "",
    footerNotes: "Facture brouillon de test E2E",
    appearance: {
      textColor: "#1a1a1a",
      headerTextColor: "#ffffff",
      headerBgColor: "#5a50ff",
    },
    customFields: [],
    isDeposit: false,
    isReverseCharge: false,
    clientPositionRight: false,
    eInvoiceStatus: "NOT_SENT",
    eInvoiceFlowType: "NONE",
    workspaceId: IDS.organizationId,
    createdBy: IDS.user,
    createdAt: now,
    updatedAt: now,
  },
  // 2. Envoyée (PENDING)
  {
    _id: IDS.invoicePending,
    prefix,
    number: "001",
    issueDate: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
    dueDate: new Date(now.getTime() + 23 * 24 * 60 * 60 * 1000),
    invoiceType: "standard",
    status: "PENDING",
    client: clientSnapshot(TEST_CLIENTS[0]),
    companyInfo: companyInfoSnapshot,
    items: [
      {
        description: "Prestation de conseil",
        quantity: 3,
        unitPrice: 800,
        vatRate: 20,
        unit: "jour",
        discount: 0,
        discountType: "PERCENTAGE",
        progressPercentage: 100,
      },
      {
        description: "Support technique",
        quantity: 5,
        unitPrice: 150,
        vatRate: 20,
        unit: "heure",
        discount: 0,
        discountType: "PERCENTAGE",
        progressPercentage: 100,
      },
    ],
    totalHT: 3150,
    totalVAT: 630,
    totalTTC: 3780,
    finalTotalHT: 3150,
    finalTotalVAT: 630,
    finalTotalTTC: 3780,
    discount: 0,
    discountType: "PERCENTAGE",
    paymentMethod: "BANK_TRANSFER",
    showBankDetails: true,
    bankDetails: TEST_USER.companyInfo.bankDetails,
    headerNotes: "",
    footerNotes: "Merci pour votre confiance.",
    appearance: {
      textColor: "#1a1a1a",
      headerTextColor: "#ffffff",
      headerBgColor: "#5a50ff",
    },
    customFields: [],
    isDeposit: false,
    isReverseCharge: false,
    clientPositionRight: false,
    eInvoiceStatus: "NOT_SENT",
    eInvoiceFlowType: "NONE",
    workspaceId: IDS.organizationId,
    createdBy: IDS.user,
    createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
  },
  // 3. Payée (COMPLETED)
  {
    _id: IDS.invoicePaid,
    prefix,
    number: "002",
    issueDate: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000),
    dueDate: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
    invoiceType: "standard",
    status: "COMPLETED",
    paymentDate: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
    paymentMethod: "BANK_TRANSFER",
    client: clientSnapshot(TEST_CLIENTS[1]),
    companyInfo: companyInfoSnapshot,
    items: [
      {
        description: "Audit SEO complet",
        quantity: 1,
        unitPrice: 1800,
        vatRate: 20,
        unit: "forfait",
        discount: 0,
        discountType: "PERCENTAGE",
        progressPercentage: 100,
      },
      {
        description: "Rédaction de rapport",
        quantity: 2,
        unitPrice: 400,
        vatRate: 20,
        unit: "unité",
        discount: 0,
        discountType: "PERCENTAGE",
        progressPercentage: 100,
      },
    ],
    totalHT: 2600,
    totalVAT: 520,
    totalTTC: 3120,
    finalTotalHT: 2600,
    finalTotalVAT: 520,
    finalTotalTTC: 3120,
    discount: 0,
    discountType: "PERCENTAGE",
    showBankDetails: true,
    bankDetails: TEST_USER.companyInfo.bankDetails,
    headerNotes: "",
    footerNotes: "Paiement reçu — merci.",
    appearance: {
      textColor: "#1a1a1a",
      headerTextColor: "#ffffff",
      headerBgColor: "#5a50ff",
    },
    customFields: [],
    isDeposit: false,
    isReverseCharge: false,
    clientPositionRight: false,
    eInvoiceStatus: "NOT_SENT",
    eInvoiceFlowType: "NONE",
    workspaceId: IDS.organizationId,
    createdBy: IDS.user,
    createdAt: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
  },
];

// ─── Quotes ─────────────────────────────────────────────────────────
const quotePrefix = `D-${currentMonth}${currentYear}`;

export const TEST_QUOTES = [
  // 1. Brouillon (DRAFT)
  {
    _id: IDS.quoteDraft,
    prefix: quotePrefix,
    number: null,
    issueDate: now,
    validUntil: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000),
    status: "DRAFT",
    client: clientSnapshot(TEST_CLIENTS[0]),
    companyInfo: companyInfoSnapshot,
    items: [
      {
        description: "Maquettes UI/UX",
        quantity: 1,
        unitPrice: 3000,
        vatRate: 20,
        unit: "forfait",
        discount: 0,
        discountType: "PERCENTAGE",
      },
    ],
    totalHT: 3000,
    totalVAT: 600,
    totalTTC: 3600,
    finalTotalHT: 3000,
    finalTotalVAT: 600,
    finalTotalTTC: 3600,
    discount: 0,
    discountType: "PERCENTAGE",
    showBankDetails: false,
    headerNotes: "",
    footerNotes: "Devis brouillon de test E2E",
    appearance: {
      textColor: "#1a1a1a",
      headerTextColor: "#ffffff",
      headerBgColor: "#5a50ff",
    },
    customFields: [],
    clientPositionRight: false,
    workspaceId: IDS.organizationId,
    createdBy: IDS.user,
    createdAt: now,
    updatedAt: now,
  },
  // 2. Envoyé (PENDING)
  {
    _id: IDS.quotePending,
    prefix: quotePrefix,
    number: "000001",
    issueDate: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
    validUntil: new Date(now.getTime() + 20 * 24 * 60 * 60 * 1000),
    status: "PENDING",
    client: clientSnapshot(TEST_CLIENTS[0]),
    companyInfo: companyInfoSnapshot,
    items: [
      {
        description: "Développement API REST",
        quantity: 10,
        unitPrice: 500,
        vatRate: 20,
        unit: "jour",
        discount: 0,
        discountType: "PERCENTAGE",
      },
    ],
    totalHT: 5000,
    totalVAT: 1000,
    totalTTC: 6000,
    finalTotalHT: 5000,
    finalTotalVAT: 1000,
    finalTotalTTC: 6000,
    discount: 0,
    discountType: "PERCENTAGE",
    showBankDetails: true,
    bankDetails: TEST_USER.companyInfo.bankDetails,
    headerNotes: "",
    footerNotes: "Devis valable 30 jours.",
    appearance: {
      textColor: "#1a1a1a",
      headerTextColor: "#ffffff",
      headerBgColor: "#5a50ff",
    },
    customFields: [],
    clientPositionRight: false,
    workspaceId: IDS.organizationId,
    createdBy: IDS.user,
    createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
  },
  // 3. Accepté (COMPLETED)
  {
    _id: IDS.quoteCompleted,
    prefix: quotePrefix,
    number: "000002",
    issueDate: new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000),
    validUntil: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000),
    status: "COMPLETED",
    client: clientSnapshot(TEST_CLIENTS[1]),
    companyInfo: companyInfoSnapshot,
    items: [
      {
        description: "Refonte site e-commerce",
        quantity: 1,
        unitPrice: 8000,
        vatRate: 20,
        unit: "forfait",
        discount: 0,
        discountType: "PERCENTAGE",
      },
    ],
    totalHT: 8000,
    totalVAT: 1600,
    totalTTC: 9600,
    finalTotalHT: 8000,
    finalTotalVAT: 1600,
    finalTotalTTC: 9600,
    discount: 0,
    discountType: "PERCENTAGE",
    showBankDetails: true,
    bankDetails: TEST_USER.companyInfo.bankDetails,
    headerNotes: "",
    footerNotes: "Devis accepté.",
    appearance: {
      textColor: "#1a1a1a",
      headerTextColor: "#ffffff",
      headerBgColor: "#5a50ff",
    },
    customFields: [],
    clientPositionRight: false,
    convertedToInvoice: null,
    workspaceId: IDS.organizationId,
    createdBy: IDS.user,
    createdAt: new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000),
  },
];

// ─── Supplier invoice (Expense for OCR testing) ─────────────────────
export const TEST_SUPPLIER_EXPENSE = {
  _id: IDS.supplierInvoice,
  title: "Facture OVH Hébergement",
  description: "Hébergement serveur dédié - Janvier 2026",
  amount: 119.88,
  currency: "EUR",
  date: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000),
  category: "SOFTWARE",
  expenseType: "ORGANIZATION",
  source: "MANUAL",
  vendor: "OVH SAS",
  vendorVatNumber: "FR22424761419",
  invoiceNumber: "FR-2026-001234",
  vatAmount: 19.98,
  vatRate: 20,
  isVatDeductible: true,
  paymentMethod: "BANK_TRANSFER",
  status: "PENDING",
  files: [],
  tags: ["hébergement", "serveur"],
  notes: "Facture fournisseur de test E2E pour OCR",
  workspaceId: IDS.organizationId,
  createdBy: IDS.user,
  isReconciled: false,
  createdAt: now,
  updatedAt: now,
};

// ─── Collections to seed / clean ────────────────────────────────────
export const SEEDED_COLLECTIONS = [
  "user",
  "organization",
  "member",
  "clients",
  "invoices",
  "quotes",
  "expenses",
  // Better Auth session collections
  "session",
  "account",
  "verification",
] as const;
