/**
 * Table de correspondance Bridge API → Plan Comptable Général (PCG 2026)
 * Version frontend pour l'affichage et la sélection de comptes.
 */

// Liste complète du Plan Comptable Général 2026
// Source: www.comptanat.fr/pcg/ et www.plancomptable.com
export const PCG_ACCOUNTS = {
  // ─── CLASSE 1 - Comptes de capitaux ───
  101: "Capital",
  1011: "Capital souscrit - non appelé",
  1012: "Capital souscrit - appelé, non versé",
  1013: "Capital souscrit - appelé, versé",
  104: "Primes liées au capital social",
  105: "Écarts de réévaluation",
  106: "Réserves",
  1061: "Réserve légale",
  1062: "Réserves indisponibles",
  1063: "Réserves statutaires ou contractuelles",
  1064: "Réserves réglementées",
  1068: "Autres réserves",
  108: "Compte de l'exploitant",
  109: "Actionnaires : Capital souscrit - non appelé",
  110: "Report à nouveau (solde créditeur)",
  119: "Report à nouveau (solde débiteur)",
  120: "Résultat de l'exercice (bénéfice)",
  129: "Résultat de l'exercice (perte)",
  131: "Subventions d'équipement",
  139: "Subventions d'investissement inscrites au compte de résultat",
  141: "Provisions réglementées relatives aux immobilisations",
  142: "Provisions réglementées relatives aux stocks",
  143: "Provisions pour hausse des prix",
  144: "Provisions réglementées relatives aux autres éléments de l'actif",
  145: "Amortissements dérogatoires",
  146: "Provision spéciale de réévaluation",
  148: "Autres provisions réglementées",
  151: "Provisions pour risques",
  1511: "Provisions pour litiges",
  1512: "Provisions pour garanties données aux clients",
  1515: "Provisions pour pertes de change",
  1518: "Autres provisions pour risques",
  152: "Provisions pour charges",
  1572: "Provisions pour gros entretien et grandes révisions",
  158: "Autres provisions pour charges",
  161: "Emprunts obligataires convertibles",
  163: "Autres emprunts obligataires",
  164: "Emprunts auprès des établissements de crédit",
  165: "Dépôts et cautionnements reçus",
  166: "Participation des salariés aux résultats",
  167: "Emprunts et dettes assortis de conditions particulières",
  168: "Autres emprunts et dettes assimilées",
  1681: "Autres emprunts",
  1685: "Rentes viagères capitalisées",
  1687: "Autres dettes",
  1688: "Intérêts courus",
  169: "Primes de remboursement des obligations",

  // ─── CLASSE 2 - Immobilisations ───
  201: "Frais d'établissement",
  2011: "Frais de constitution",
  2013: "Frais de premier établissement",
  203: "Frais de développement",
  205: "Concessions, brevets, licences, marques, logiciels",
  206: "Droit au bail",
  207: "Fonds commercial",
  208: "Autres immobilisations incorporelles",
  211: "Terrains",
  212: "Agencements et aménagements de terrains",
  213: "Constructions",
  2131: "Bâtiments",
  2135: "Installations générales, agencements, aménagements",
  2138: "Ouvrages d'infrastructure",
  214: "Constructions sur sol d'autrui",
  215: "Installations techniques, matériels et outillage industriels",
  2151: "Installations complexes spécialisées",
  2154: "Matériel industriel",
  2155: "Outillage industriel",
  218: "Autres immobilisations corporelles",
  2181: "Installations générales, agencements divers",
  2182: "Matériel de transport",
  2183: "Matériel de bureau et matériel informatique",
  2184: "Mobilier",
  2185: "Cheptel",
  2186: "Emballages récupérables",
  231: "Immobilisations corporelles en cours",
  232: "Immobilisations incorporelles en cours",
  237: "Avances et acomptes versés sur immobilisations incorporelles",
  238: "Avances et acomptes versés sur immobilisations corporelles",
  261: "Titres de participation",
  266: "Autres formes de participation",
  267: "Créances rattachées à des participations",
  268: "Créances rattachées à des sociétés en participation",
  269: "Versements restant à effectuer sur titres de participation non libérés",
  271: "Titres immobilisés autres que les TIAP (droit de propriété)",
  272: "Titres immobilisés (droit de créance)",
  273: "Titres immobilisés de l'activité de portefeuille (TIAP)",
  274: "Prêts",
  275: "Dépôts et cautionnements versés",
  276: "Autres créances immobilisées",
  277: "Actions propres ou parts propres",
  279: "Versements restant à effectuer sur titres immobilisés non libérés",
  280: "Amortissements des immobilisations incorporelles",
  281: "Amortissements des immobilisations corporelles",
  290: "Dépréciations des immobilisations incorporelles",
  291: "Dépréciations des immobilisations corporelles",
  293: "Dépréciations des immobilisations en cours",
  296: "Dépréciations des participations et créances rattachées",
  297: "Dépréciations des autres immobilisations financières",

  // ─── CLASSE 3 - Stocks et en-cours ───
  31: "Matières premières",
  32: "Autres approvisionnements",
  33: "En-cours de production de biens",
  34: "En-cours de production de services",
  35: "Stocks de produits",
  351: "Produits intermédiaires",
  355: "Produits finis",
  358: "Produits résiduels",
  36: "Stocks provenant d'immobilisations",
  37: "Stocks de marchandises",
  38: "Stocks en voie d'acheminement",
  39: "Dépréciations des stocks et en-cours",

  // ─── CLASSE 4 - Comptes de tiers ───
  401: "Fournisseurs",
  4011: "Fournisseurs - Achats de biens ou prestations",
  4017: "Fournisseurs - Retenues de garantie",
  403: "Fournisseurs - Effets à payer",
  404: "Fournisseurs d'immobilisations",
  405: "Fournisseurs d'immobilisations - Effets à payer",
  408: "Fournisseurs - Factures non parvenues",
  409: "Fournisseurs débiteurs",
  4091: "Fournisseurs - Avances et acomptes versés",
  4096: "Fournisseurs - Créances pour emballages et matériel à rendre",
  4098: "Rabais, remises, ristournes à obtenir",
  411: "Clients",
  4111: "Clients - Ventes de biens ou prestations",
  4117: "Clients - Retenues de garantie",
  413: "Clients - Effets à recevoir",
  416: "Clients douteux ou litigieux",
  418: "Clients - Produits non encore facturés",
  419: "Clients créditeurs",
  4191: "Clients - Avances et acomptes reçus sur commandes",
  4196: "Clients - Dettes pour emballages et matériel consignés",
  4198: "Rabais, remises, ristournes à accorder",
  421: "Personnel - Rémunérations dues",
  422: "Comités d'entreprise, d'établissement",
  424: "Participation des salariés aux résultats",
  425: "Personnel - Avances et acomptes",
  426: "Personnel - Dépôts",
  427: "Personnel - Oppositions",
  428: "Personnel - Charges à payer et produits à recevoir",
  431: "Sécurité sociale",
  437: "Autres organismes sociaux",
  438: "Organismes sociaux - Charges à payer et produits à recevoir",
  441: "État - Subventions à recevoir",
  442: "État - Impôts et taxes recouvrables sur des tiers",
  443: "Opérations particulières avec l'État",
  444: "État - Impôts sur les bénéfices",
  445: "État - Taxes sur le chiffre d'affaires",
  4452: "TVA due intracommunautaire",
  4455: "TVA à décaisser",
  4456: "TVA déductible",
  44566: "TVA sur autres biens et services",
  44562: "TVA sur immobilisations",
  4457: "TVA collectée",
  4458: "TVA à régulariser ou en attente",
  446: "Obligations cautionnées",
  447: "Autres impôts, taxes et versements assimilés",
  448: "État - Charges à payer et produits à recevoir",
  451: "Groupe",
  455: "Associés - Comptes courants",
  456: "Associés - Opérations sur le capital",
  457: "Associés - Dividendes à payer",
  458: "Associés - Opérations faites en commun et en GIE",
  462: "Créances sur cessions d'immobilisations",
  464: "Dettes sur acquisitions de valeurs mobilières de placement",
  465: "Créances sur cessions de valeurs mobilières de placement",
  467: "Autres comptes débiteurs ou créditeurs",
  468: "Divers - Charges à payer et produits à recevoir",
  471: "Comptes d'attente",
  472: "Comptes transitoires",
  475: "Différences sur fonds de caisse",
  476: "Différences de conversion - Actif",
  477: "Différences de conversion - Passif",
  478: "Autres comptes transitoires",
  481: "Charges à répartir sur plusieurs exercices",
  486: "Charges constatées d'avance",
  487: "Produits constatés d'avance",
  488: "Comptes de répartition périodique des charges et des produits",
  491: "Dépréciations des comptes de clients",
  495: "Dépréciations des comptes du groupe et des associés",
  496: "Dépréciations des comptes de débiteurs divers",

  // ─── CLASSE 5 - Comptes financiers ───
  501: "Parts dans des entreprises liées",
  502: "Actions propres",
  503: "Actions",
  504: "Autres titres conférant un droit de propriété",
  505: "Obligations et bons émis par la société et rachetés",
  506: "Obligations",
  507: "Bons du Trésor et bons de caisse à court terme",
  508: "Autres valeurs mobilières de placement",
  509: "Versements restant à effectuer sur valeurs mobilières non libérées",
  511: "Valeurs à l'encaissement",
  512: "Banques",
  514: "Chèques postaux",
  515: "Caisses du Trésor et des établissements publics",
  516: "Sociétés de bourse",
  517: "Autres organismes financiers",
  518: "Intérêts courus",
  519: "Concours bancaires courants",
  5191: "Crédits de mobilisation de créances commerciales (CMCC)",
  5193: "Mobilisations de créances nées à l'étranger",
  5198: "Intérêts courus sur concours bancaires courants",
  53: "Caisse",
  531: "Caisse siège social",
  532: "Caisse succursale (ou usine) A",
  54: "Régies d'avances et accréditifs",
  58: "Virements internes",
  59: "Dépréciations des comptes financiers",

  // ─── CLASSE 6 - Comptes de charges ───
  601: "Achats stockés - Matières premières (et fournitures)",
  602: "Achats stockés - Autres approvisionnements",
  6021: "Matières consommables",
  6022: "Fournitures consommables",
  60221: "Combustibles",
  60222: "Produits d'entretien",
  60223: "Fournitures d'atelier et d'usine",
  60224: "Fournitures de magasin",
  60225: "Fournitures de bureau",
  6026: "Emballages",
  603: "Variations des stocks (approvisionnements et marchandises)",
  6031: "Variation des stocks de matières premières",
  6032: "Variation des stocks des autres approvisionnements",
  6037: "Variation des stocks de marchandises",
  604: "Achats d'études et prestations de services",
  605: "Achats de matériel, équipements et travaux",
  606: "Achats non stockés de matières et fournitures",
  6061: "Fournitures non stockables (eau, énergie)",
  60611: "Eau",
  60612: "Électricité",
  60613: "Gaz",
  6063: "Fournitures d'entretien et de petit équipement",
  6064: "Fournitures administratives",
  6068: "Autres matières et fournitures",
  607: "Achats de marchandises",
  608: "Frais accessoires d'achat",
  609: "Rabais, remises et ristournes obtenus sur achats",
  611: "Sous-traitance générale",
  612: "Redevances de crédit-bail",
  6122: "Crédit-bail mobilier",
  6125: "Crédit-bail immobilier",
  613: "Locations",
  6132: "Locations immobilières",
  6135: "Locations mobilières",
  6136: "Malis sur emballages",
  614: "Charges locatives et de copropriété",
  615: "Entretien et réparations",
  6152: "Entretien et réparations sur biens immobiliers",
  6155: "Entretien et réparations sur biens mobiliers",
  6156: "Maintenance",
  616: "Primes d'assurances",
  6161: "Multirisques",
  6162: "Assurance obligatoire dommage construction",
  6163: "Assurance - transport",
  6164: "Risques d'exploitation",
  6165: "Insolvabilité clients",
  617: "Études et recherches",
  618: "Divers",
  6181: "Documentation générale",
  6183: "Documentation technique",
  6185: "Frais de colloques, séminaires, conférences",
  619: "Rabais, remises et ristournes obtenus sur services extérieurs",
  621: "Personnel extérieur à l'entreprise",
  6211: "Personnel intérimaire",
  6214: "Personnel détaché ou prêté à l'entreprise",
  622: "Rémunérations d'intermédiaires et honoraires",
  6221: "Commissions et courtages sur achats",
  6222: "Commissions et courtages sur ventes",
  6226: "Honoraires",
  6227: "Frais d'actes et de contentieux",
  6228: "Divers",
  623: "Publicité, publications, relations publiques",
  6231: "Annonces et insertions",
  6232: "Échantillons",
  6233: "Foires et expositions",
  6234: "Cadeaux à la clientèle",
  6235: "Primes",
  6236: "Catalogues et imprimés",
  6237: "Publications",
  6238: "Divers (pourboires, dons courants...)",
  624: "Transports de biens et transports collectifs du personnel",
  6241: "Transports sur achats",
  6242: "Transports sur ventes",
  6243: "Transports entre établissements ou chantiers",
  6244: "Transports administratifs",
  6247: "Transports collectifs du personnel",
  6248: "Divers",
  625: "Déplacements, missions et réceptions",
  6251: "Voyages et déplacements",
  6255: "Frais de déménagement",
  6256: "Missions",
  6257: "Réceptions",
  626: "Frais postaux et de télécommunications",
  627: "Services bancaires et assimilés",
  6271: "Frais sur titres (achat, vente, garde)",
  6272: "Commissions et frais sur émission d'emprunts",
  6275: "Frais sur effets",
  6276: "Location de coffres",
  6278: "Autres frais et commissions sur prestations de services",
  628: "Divers",
  6281: "Concours divers (cotisations)",
  6284: "Frais de recrutement de personnel",
  629: "Rabais, remises, ristournes obtenus sur autres services extérieurs",
  631: "Impôts, taxes sur rémunérations (administrations des impôts)",
  6311: "Taxe sur les salaires",
  6312: "Taxe d'apprentissage",
  6313: "Participation des employeurs à la formation continue",
  6314: "Cotisation pour défaut d'investissement obligatoire dans la construction",
  633: "Impôts, taxes sur rémunérations (autres organismes)",
  6331: "Versement de transport",
  6332: "Allocations logement",
  6333: "Contribution unique à la formation professionnelle",
  6334: "Participation des employeurs à l'effort de construction",
  6335: "Versements libératoires taxe d'apprentissage",
  635: "Autres impôts, taxes et versements assimilés (admin. des impôts)",
  6351: "Impôts directs (sauf impôts sur les bénéfices)",
  63511: "Contribution économique territoriale",
  63512: "Taxes foncières",
  63513: "Autres impôts locaux",
  63514: "Taxe sur les véhicules des sociétés",
  6352: "Taxes sur le chiffre d'affaires non récupérables",
  6353: "Impôts indirects",
  6354: "Droits d'enregistrement et de timbre",
  637: "Autres impôts, taxes et versements assimilés (autres organismes)",
  6371: "Contribution sociale de solidarité à la charge des sociétés",
  6378: "Taxes diverses",
  641: "Rémunérations du personnel",
  6411: "Salaires, appointements",
  6412: "Congés payés",
  6413: "Primes et gratifications",
  6414: "Indemnités et avantages divers",
  6415: "Supplément familial",
  644: "Rémunération du travail de l'exploitant",
  645: "Charges de sécurité sociale et de prévoyance",
  6451: "Cotisations à l'URSSAF",
  6452: "Cotisations aux mutuelles",
  6453: "Cotisations aux caisses de retraites",
  6454: "Cotisations à Pôle emploi",
  6458: "Cotisations aux autres organismes sociaux",
  646: "Cotisations sociales personnelles de l'exploitant",
  647: "Autres charges sociales",
  6471: "Prestations directes",
  6472: "Versements au comité d'entreprise",
  6475: "Médecine du travail, pharmacie",
  648: "Autres charges de personnel",
  649: "Remboursement de charges de personnel",
  651: "Redevances pour concessions, brevets, licences, logiciels",
  6511: "Redevances pour concessions, brevets, licences",
  6516: "Droits d'auteur et de reproduction",
  6518: "Autres droits et valeurs similaires",
  653: "Jetons de présence",
  654: "Pertes sur créances irrécouvrables",
  6541: "Créances de l'exercice",
  6544: "Créances des exercices antérieurs",
  655: "Quotes-parts de résultat sur opérations faites en commun",
  658: "Charges diverses de gestion courante",
  6581: "Pénalités sur marchés et dédits payés sur achats et ventes",
  6582: "Pénalités, amendes fiscales et pénales",
  6583: "Malis provenant de clauses d'indexation",
  6588: "Autres charges diverses de gestion courante",
  661: "Charges d'intérêts",
  6611: "Intérêts des emprunts et dettes",
  6615: "Intérêts des comptes courants et des dépôts créditeurs",
  6616: "Intérêts bancaires et sur opérations de financement",
  6617: "Intérêts des obligations cautionnées",
  664: "Pertes sur créances liées à des participations",
  665: "Escomptes accordés",
  666: "Pertes de change",
  667: "Charges nettes sur cessions de VMP",
  668: "Autres charges financières",
  671: "Charges exceptionnelles sur opérations de gestion",
  6711: "Pénalités sur marchés et dédits payés",
  6712: "Pénalités, amendes fiscales et pénales",
  6713: "Dons, libéralités",
  6714: "Créances devenues irrécouvrables",
  6717: "Rappels d'impôts (autres que impôts sur les bénéfices)",
  6718: "Autres charges exceptionnelles sur opérations de gestion",
  672: "Charges sur exercices antérieurs",
  675: "Valeurs comptables des éléments d'actif cédés",
  6751: "Immobilisations incorporelles",
  6752: "Immobilisations corporelles",
  6756: "Immobilisations financières",
  678: "Autres charges exceptionnelles",
  6781: "Malis provenant de clauses d'indexation",
  6788: "Charges exceptionnelles diverses",
  681: "Dotations aux amortissements, dépréciations et provisions (exploitation)",
  6811: "Dotations aux amortissements des immobilisations incorporelles et corporelles",
  6815: "Dotations aux provisions pour risques et charges d'exploitation",
  6816: "Dotations aux dépréciations des immobilisations incorporelles et corporelles",
  6817: "Dotations aux dépréciations des actifs circulants",
  686: "Dotations aux amortissements, dépréciations et provisions (financières)",
  687: "Dotations aux amortissements, dépréciations et provisions (exceptionnelles)",
  691: "Participation des salariés aux résultats",
  695: "Impôts sur les bénéfices",
  6951: "Impôts dus en France",
  6952: "Contribution additionnelle à l'impôt sur les bénéfices",
  6954: "Impôts dus à l'étranger",
  697: "Imposition forfaitaire annuelle des sociétés",
  698: "Intégration fiscale",
  699: "Produits - Reports en arrière des déficits",

  // ─── CLASSE 7 - Comptes de produits ───
  701: "Ventes de produits finis",
  702: "Ventes de produits intermédiaires",
  703: "Ventes de produits résiduels",
  704: "Travaux",
  705: "Études",
  706: "Prestations de services",
  707: "Ventes de marchandises",
  708: "Produits des activités annexes",
  7081: "Produits des services exploités dans l'intérêt du personnel",
  7082: "Commissions et courtages",
  7083: "Locations diverses",
  7084: "Mise à disposition de personnel facturée",
  7085: "Ports et frais accessoires facturés",
  7086: "Bonis sur reprises d'emballages consignés",
  7087: "Bonifications obtenues des clients et primes sur ventes",
  7088: "Autres produits d'activités annexes",
  709: "Rabais, remises et ristournes accordés par l'entreprise",
  713: "Variation des stocks (en-cours de production, produits)",
  7133: "Variation des en-cours de production de biens",
  7134: "Variation des en-cours de production de services",
  7135: "Variation des stocks de produits",
  72: "Production immobilisée",
  721: "Immobilisations incorporelles",
  722: "Immobilisations corporelles",
  74: "Subventions d'exploitation",
  741: "Subventions d'exploitation",
  75: "Autres produits de gestion courante",
  751: "Redevances pour concessions, brevets, licences, logiciels",
  752: "Revenus des immeubles non affectés à des activités professionnelles",
  753: "Jetons de présence et rémunérations d'administrateurs",
  754: "Ristournes perçues des coopératives",
  755: "Quotes-parts de résultat sur opérations faites en commun",
  758: "Produits divers de gestion courante",
  7581: "Dédits et pénalités perçus sur achats et ventes",
  7583: "Rentrées sur créances amorties",
  7584: "Dégrèvements d'impôts (autres que impôts sur bénéfices)",
  7587: "Indemnités d'assurances",
  7588: "Autres produits divers de gestion courante",
  761: "Produits de participations",
  762: "Produits des autres immobilisations financières",
  763: "Revenus des autres créances",
  764: "Revenus des valeurs mobilières de placement",
  765: "Escomptes obtenus",
  766: "Gains de change",
  767: "Produits nets sur cessions de VMP",
  768: "Autres produits financiers",
  771: "Produits exceptionnels sur opérations de gestion",
  7711: "Dédits et pénalités perçus",
  7713: "Libéralités reçues",
  7714: "Rentrées sur créances amorties",
  7715: "Subventions d'équilibre",
  7717: "Dégrèvements d'impôts (autres que sur bénéfices)",
  7718: "Autres produits exceptionnels sur opérations de gestion",
  772: "Produits sur exercices antérieurs",
  775: "Produits des cessions d'éléments d'actif",
  7751: "Immobilisations incorporelles",
  7752: "Immobilisations corporelles",
  7756: "Immobilisations financières",
  777: "Quote-part des subventions d'investissement virée au résultat",
  778: "Autres produits exceptionnels",
  781: "Reprises sur amortissements, dépréciations et provisions (exploitation)",
  786: "Reprises sur dépréciations et provisions (financières)",
  787: "Reprises sur dépréciations et provisions (exceptionnelles)",
  791: "Transferts de charges d'exploitation",
  796: "Transferts de charges financières",
  797: "Transferts de charges exceptionnelles",

  // ─── CLASSE 8 - Comptes spéciaux ───
  801: "Engagements donnés par l'entité",
  802: "Engagements reçus par l'entité",
  809: "Contrepartie des engagements",
  88: "Résultat en instance d'affectation",
  89: "Bilan",
  678: "Autres charges exceptionnelles",
  695: "Impôts sur les bénéfices",
  // Classe 7 - Produits
  701: "Ventes de produits finis",
  706: "Prestations de services",
  707: "Ventes de marchandises",
  7083: "Locations diverses",
  741: "Subventions d'exploitation",
  752: "Revenus des immeubles non affectés aux activités pro.",
  758: "Produits divers de gestion courante",
  764: "Revenus des valeurs mobilières de placement",
  762: "Produits des autres immobilisations financières",
  765: "Escomptes obtenus",
  768: "Autres produits financiers",
  778: "Autres produits exceptionnels",
  // Comptes d'attente
  471: "Comptes d'attente",
  164: "Emprunts auprès des établissements de crédit",
};

// Mapping Bridge → PCG
export const BRIDGE_TO_PCG = {
  // INCOMES
  3: {
    pcg: "758",
    label: "Other incomes",
    parent: "Incomes",
    confidence: "medium",
    alt: ["778"],
  },
  80: {
    pcg: "764",
    label: "Interest incomes",
    parent: "Incomes",
    confidence: "high",
    alt: ["762"],
  },
  230: {
    pcg: "641",
    label: "Salaries",
    parent: "Incomes",
    confidence: "low",
    alt: ["644"],
  },
  231: {
    pcg: "707",
    label: "Sales",
    parent: "Incomes",
    confidence: "high",
    alt: ["701"],
  },
  232: {
    pcg: "706",
    label: "Services",
    parent: "Incomes",
    confidence: "high",
    alt: [],
  },
  233: {
    pcg: "758",
    label: "Extra incomes",
    parent: "Incomes",
    confidence: "medium",
    alt: ["778"],
  },
  271: {
    pcg: "512",
    label: "Deposit",
    parent: "Incomes",
    confidence: "medium",
    alt: [],
  },
  279: {
    pcg: "758",
    label: "Retirement",
    parent: "Incomes",
    confidence: "low",
    alt: [],
  },
  282: {
    pcg: "58",
    label: "Internal transfer",
    parent: "Incomes",
    confidence: "high",
    alt: [],
  },
  283: {
    pcg: "765",
    label: "Refunds",
    parent: "Incomes",
    confidence: "medium",
    alt: ["758"],
  },
  289: {
    pcg: "512",
    label: "Savings",
    parent: "Incomes",
    confidence: "high",
    alt: [],
  },
  314: {
    pcg: "752",
    label: "Rent (income)",
    parent: "Incomes",
    confidence: "high",
    alt: ["7083"],
  },
  327: {
    pcg: "758",
    label: "Pension",
    parent: "Incomes",
    confidence: "low",
    alt: [],
  },
  441893: {
    pcg: "741",
    label: "Grants",
    parent: "Incomes",
    confidence: "high",
    alt: [],
  },
  441894: {
    pcg: "512",
    label: "Loans (income)",
    parent: "Incomes",
    confidence: "high",
    alt: [],
  },

  // TAXES
  206: {
    pcg: "635",
    label: "Taxes - Others",
    parent: "Taxes",
    confidence: "medium",
    alt: ["637"],
  },
  207: {
    pcg: "6582",
    label: "Fine",
    parent: "Taxes",
    confidence: "high",
    alt: [],
  },
  208: {
    pcg: "444",
    label: "Income taxes",
    parent: "Taxes",
    confidence: "high",
    alt: ["695"],
  },
  209: {
    pcg: "63512",
    label: "Property taxes",
    parent: "Taxes",
    confidence: "high",
    alt: [],
  },
  302: {
    pcg: "635",
    label: "Taxes (generic)",
    parent: "Taxes",
    confidence: "medium",
    alt: ["631", "633"],
  },
  441988: {
    pcg: "4455",
    label: "VAT",
    parent: "Taxes",
    confidence: "high",
    alt: ["4456"],
  },

  // MISC. EXPENSES
  1: {
    pcg: "471",
    label: "Uncategorized",
    parent: "Misc.",
    confidence: "low",
    alt: [],
  },
  276: {
    pcg: "606",
    label: "Others spending",
    parent: "Misc.",
    confidence: "low",
    alt: ["658"],
  },
  278: {
    pcg: "616",
    label: "Insurance",
    parent: "Misc.",
    confidence: "high",
    alt: ["6161", "6164"],
  },
  294: {
    pcg: "6713",
    label: "Charity",
    parent: "Misc.",
    confidence: "high",
    alt: [],
  },
  308: {
    pcg: "606",
    label: "Tobacco",
    parent: "Misc.",
    confidence: "medium",
    alt: [],
  },
  324: {
    pcg: "6063",
    label: "Laundry / Dry cleaning",
    parent: "Misc.",
    confidence: "medium",
    alt: ["625"],
  },

  // HOME
  216: {
    pcg: "6132",
    label: "Rent (expense)",
    parent: "Home",
    confidence: "high",
    alt: ["614"],
  },
  217: {
    pcg: "6061",
    label: "Electricity",
    parent: "Home",
    confidence: "high",
    alt: [],
  },
  218: {
    pcg: "6061",
    label: "Gas",
    parent: "Home",
    confidence: "high",
    alt: [],
  },
  220: {
    pcg: "606",
    label: "Home - Others",
    parent: "Home",
    confidence: "low",
    alt: ["615"],
  },
  221: {
    pcg: "615",
    label: "Home improvement",
    parent: "Home",
    confidence: "medium",
    alt: ["2183"],
  },
  222: {
    pcg: "6152",
    label: "Maintenance",
    parent: "Home",
    confidence: "high",
    alt: ["6156"],
  },
  246: {
    pcg: "6161",
    label: "Home insurance",
    parent: "Home",
    confidence: "high",
    alt: [],
  },
  293: {
    pcg: "6061",
    label: "Water",
    parent: "Home",
    confidence: "high",
    alt: [],
  },
  323: {
    pcg: "6155",
    label: "Lawn & Garden",
    parent: "Home",
    confidence: "medium",
    alt: ["6063"],
  },
  328: {
    pcg: "6061",
    label: "Misc. utilities",
    parent: "Home",
    confidence: "medium",
    alt: [],
  },

  // SHOPPING
  183: {
    pcg: "6234",
    label: "Gifts",
    parent: "Shopping",
    confidence: "high",
    alt: ["6238"],
  },
  184: {
    pcg: "6064",
    label: "High Tech",
    parent: "Shopping",
    confidence: "medium",
    alt: ["2183"],
  },
  186: {
    pcg: "606",
    label: "Shopping - Others",
    parent: "Shopping",
    confidence: "low",
    alt: ["6063"],
  },
  243: {
    pcg: "6181",
    label: "Books",
    parent: "Shopping",
    confidence: "high",
    alt: ["6183"],
  },
  262: {
    pcg: "606",
    label: "Sporting goods",
    parent: "Shopping",
    confidence: "low",
    alt: [],
  },
  272: {
    pcg: "606",
    label: "Clothing & Shoes",
    parent: "Shopping",
    confidence: "low",
    alt: ["6063"],
  },
  318: {
    pcg: "606",
    label: "Music",
    parent: "Shopping",
    confidence: "low",
    alt: [],
  },
  319: {
    pcg: "606",
    label: "Movies",
    parent: "Shopping",
    confidence: "low",
    alt: [],
  },
  441888: {
    pcg: "651",
    label: "Licences",
    parent: "Shopping",
    confidence: "high",
    alt: ["205"],
  },

  // HEALTH
  236: {
    pcg: "648",
    label: "Pharmacy",
    parent: "Health",
    confidence: "medium",
    alt: ["646"],
  },
  245: {
    pcg: "6452",
    label: "Health insurance",
    parent: "Health",
    confidence: "high",
    alt: ["646"],
  },
  261: {
    pcg: "648",
    label: "Doctor",
    parent: "Health",
    confidence: "medium",
    alt: ["646"],
  },
  268: {
    pcg: "648",
    label: "Health - Others",
    parent: "Health",
    confidence: "low",
    alt: ["646"],
  },
  322: {
    pcg: "648",
    label: "Optician / Eyecare",
    parent: "Health",
    confidence: "low",
    alt: [],
  },
  325: {
    pcg: "648",
    label: "Dentist",
    parent: "Health",
    confidence: "low",
    alt: ["646"],
  },

  // BANK
  79: {
    pcg: "627",
    label: "Banking fees",
    parent: "Bank",
    confidence: "high",
    alt: ["6278"],
  },
  89: {
    pcg: "6611",
    label: "Mortgage refund",
    parent: "Bank",
    confidence: "high",
    alt: ["164"],
  },
  191: {
    pcg: "627",
    label: "Monthly Debit",
    parent: "Bank",
    confidence: "medium",
    alt: [],
  },
  192: {
    pcg: "512",
    label: "Savings (bank)",
    parent: "Bank",
    confidence: "high",
    alt: [],
  },
  194: {
    pcg: "6611",
    label: "Mortgage",
    parent: "Bank",
    confidence: "high",
    alt: ["164"],
  },
  195: {
    pcg: "627",
    label: "Bank - Others",
    parent: "Bank",
    confidence: "medium",
    alt: [],
  },
  306: {
    pcg: "627",
    label: "Banking services",
    parent: "Bank",
    confidence: "high",
    alt: ["6278"],
  },
  756587: {
    pcg: "627",
    label: "Payment incidents",
    parent: "Bank",
    confidence: "high",
    alt: ["6616"],
  },

  // AUTO & TRANSPORT
  84: {
    pcg: "6251",
    label: "Auto - Others",
    parent: "Transport",
    confidence: "medium",
    alt: ["624"],
  },
  87: {
    pcg: "6061",
    label: "Gas & Fuel",
    parent: "Transport",
    confidence: "high",
    alt: [],
  },
  196: {
    pcg: "6251",
    label: "Public transportation",
    parent: "Transport",
    confidence: "high",
    alt: [],
  },
  197: {
    pcg: "6251",
    label: "Train ticket",
    parent: "Transport",
    confidence: "high",
    alt: [],
  },
  198: {
    pcg: "6251",
    label: "Plane ticket",
    parent: "Transport",
    confidence: "high",
    alt: [],
  },
  247: {
    pcg: "6163",
    label: "Auto insurance",
    parent: "Transport",
    confidence: "high",
    alt: [],
  },
  251: {
    pcg: "6251",
    label: "Parking",
    parent: "Transport",
    confidence: "high",
    alt: [],
  },
  264: {
    pcg: "6135",
    label: "Car rental",
    parent: "Transport",
    confidence: "high",
    alt: ["6251"],
  },
  288: {
    pcg: "6155",
    label: "Car maintenance",
    parent: "Transport",
    confidence: "high",
    alt: [],
  },
  309: {
    pcg: "6251",
    label: "Tolls",
    parent: "Transport",
    confidence: "high",
    alt: [],
  },

  // BUSINESS SERVICES
  90: {
    pcg: "604",
    label: "Business expenses",
    parent: "Business",
    confidence: "medium",
    alt: ["611"],
  },
  202: {
    pcg: "623",
    label: "Advertising",
    parent: "Business",
    confidence: "high",
    alt: ["6231"],
  },
  203: {
    pcg: "604",
    label: "Office services",
    parent: "Business",
    confidence: "medium",
    alt: ["628"],
  },
  204: {
    pcg: "6241",
    label: "Shipping",
    parent: "Business",
    confidence: "high",
    alt: ["626"],
  },
  205: {
    pcg: "6236",
    label: "Printing",
    parent: "Business",
    confidence: "medium",
    alt: ["6064"],
  },
  265: {
    pcg: "6064",
    label: "Office supplies",
    parent: "Business",
    confidence: "high",
    alt: [],
  },
  270: {
    pcg: "604",
    label: "Online services",
    parent: "Business",
    confidence: "medium",
    alt: ["651"],
  },
  274: {
    pcg: "6064",
    label: "Office supplies (alt)",
    parent: "Business",
    confidence: "high",
    alt: [],
  },
  441886: {
    pcg: "645",
    label: "Employer contributions",
    parent: "Business",
    confidence: "high",
    alt: ["6451", "6453"],
  },
  441889: {
    pcg: "6226",
    label: "Accounting",
    parent: "Business",
    confidence: "high",
    alt: [],
  },
  441890: {
    pcg: "6411",
    label: "Salaries (expense)",
    parent: "Business",
    confidence: "high",
    alt: [],
  },
  441891: {
    pcg: "6411",
    label: "Salary of executives",
    parent: "Business",
    confidence: "high",
    alt: ["644"],
  },
  441892: {
    pcg: "6284",
    label: "Hiring fees",
    parent: "Business",
    confidence: "high",
    alt: [],
  },
  441895: {
    pcg: "6226",
    label: "Consulting",
    parent: "Business",
    confidence: "high",
    alt: [],
  },
  441896: {
    pcg: "611",
    label: "Outsourcing",
    parent: "Business",
    confidence: "high",
    alt: [],
  },
  441897: {
    pcg: "6452",
    label: "Disability Insurance",
    parent: "Business",
    confidence: "high",
    alt: ["616"],
  },
  441898: {
    pcg: "6333",
    label: "Training taxes",
    parent: "Business",
    confidence: "high",
    alt: [],
  },
  441899: {
    pcg: "6227",
    label: "Legal Fees",
    parent: "Business",
    confidence: "high",
    alt: [],
  },
  441900: {
    pcg: "623",
    label: "Marketing",
    parent: "Business",
    confidence: "high",
    alt: [],
  },

  // EDUCATION & CHILDREN
  237: {
    pcg: "6185",
    label: "Education - Others",
    parent: "Education",
    confidence: "low",
    alt: ["618"],
  },
  238: {
    pcg: "6064",
    label: "School supplies",
    parent: "Education",
    confidence: "low",
    alt: [],
  },
  239: {
    pcg: "6185",
    label: "Tuition",
    parent: "Education",
    confidence: "medium",
    alt: [],
  },
  240: {
    pcg: "678",
    label: "Pension (children)",
    parent: "Education",
    confidence: "low",
    alt: [],
  },
  241: {
    pcg: "678",
    label: "Student housing",
    parent: "Education",
    confidence: "low",
    alt: [],
  },
  259: {
    pcg: "6611",
    label: "Student loan",
    parent: "Education",
    confidence: "low",
    alt: [],
  },
  266: {
    pcg: "606",
    label: "Toys",
    parent: "Education",
    confidence: "low",
    alt: [],
  },
  267: {
    pcg: "648",
    label: "Baby-sitter & Daycare",
    parent: "Education",
    confidence: "low",
    alt: [],
  },

  // FOOD & DINING
  83: {
    pcg: "6257",
    label: "Restaurants",
    parent: "Food",
    confidence: "high",
    alt: ["6256"],
  },
  188: {
    pcg: "606",
    label: "Food - Others",
    parent: "Food",
    confidence: "medium",
    alt: ["6257"],
  },
  260: {
    pcg: "6256",
    label: "Fast foods",
    parent: "Food",
    confidence: "medium",
    alt: ["6257"],
  },
  273: {
    pcg: "606",
    label: "Supermarkets",
    parent: "Food",
    confidence: "medium",
    alt: ["601", "607"],
  },
  313: {
    pcg: "6257",
    label: "Coffee shop",
    parent: "Food",
    confidence: "medium",
    alt: ["6256"],
  },

  // ENTERTAINMENT
  223: {
    pcg: "6257",
    label: "Entertainment - Others",
    parent: "Entertainment",
    confidence: "low",
    alt: [],
  },
  224: {
    pcg: "606",
    label: "Pets",
    parent: "Entertainment",
    confidence: "low",
    alt: [],
  },
  226: {
    pcg: "606",
    label: "Hobbies",
    parent: "Entertainment",
    confidence: "low",
    alt: [],
  },
  227: {
    pcg: "6257",
    label: "Bars & Clubs",
    parent: "Entertainment",
    confidence: "low",
    alt: [],
  },
  242: {
    pcg: "606",
    label: "Sports",
    parent: "Entertainment",
    confidence: "low",
    alt: ["6281"],
  },
  244: {
    pcg: "6257",
    label: "Arts & Amusement",
    parent: "Entertainment",
    confidence: "low",
    alt: [],
  },
  249: {
    pcg: "6251",
    label: "Travels / Vacation",
    parent: "Entertainment",
    confidence: "medium",
    alt: ["625"],
  },
  263: {
    pcg: "6256",
    label: "Hotels",
    parent: "Entertainment",
    confidence: "high",
    alt: [],
  },
  269: {
    pcg: "6257",
    label: "Amusements",
    parent: "Entertainment",
    confidence: "low",
    alt: [],
  },
  310: {
    pcg: "606",
    label: "Winter sports",
    parent: "Entertainment",
    confidence: "low",
    alt: [],
  },
  320: {
    pcg: "6257",
    label: "Eating out",
    parent: "Entertainment",
    confidence: "medium",
    alt: ["6256"],
  },

  // BILLS & UTILITIES
  180: {
    pcg: "626",
    label: "Internet",
    parent: "Bills",
    confidence: "high",
    alt: [],
  },
  219: {
    pcg: "626",
    label: "Cable TV",
    parent: "Bills",
    confidence: "low",
    alt: ["606"],
  },
  258: {
    pcg: "626",
    label: "Home phone",
    parent: "Bills",
    confidence: "high",
    alt: [],
  },
  277: {
    pcg: "626",
    label: "Mobile phone",
    parent: "Bills",
    confidence: "high",
    alt: [],
  },
  280: {
    pcg: "651",
    label: "Subscription - Others",
    parent: "Bills",
    confidence: "medium",
    alt: ["606"],
  },

  // WITHDRAWALS, CHECKS & TRANSFER
  78: {
    pcg: "512",
    label: "Transfer",
    parent: "Transfers",
    confidence: "medium",
    alt: ["58"],
  },
  85: {
    pcg: "53",
    label: "Withdrawals",
    parent: "Transfers",
    confidence: "high",
    alt: [],
  },
  88: {
    pcg: "512",
    label: "Checks",
    parent: "Transfers",
    confidence: "medium",
    alt: [],
  },
  326: {
    pcg: "58",
    label: "Internal transfer",
    parent: "Transfers",
    confidence: "high",
    alt: [],
  },

  // PERSONAL CARE
  235: {
    pcg: "606",
    label: "Hairdresser",
    parent: "Personal care",
    confidence: "low",
    alt: [],
  },
  248: {
    pcg: "606",
    label: "Cosmetics",
    parent: "Personal care",
    confidence: "low",
    alt: [],
  },
  316: {
    pcg: "606",
    label: "Spa & Massage",
    parent: "Personal care",
    confidence: "low",
    alt: [],
  },
  317: {
    pcg: "606",
    label: "Personal care - Others",
    parent: "Personal care",
    confidence: "low",
    alt: [],
  },
  321: {
    pcg: "606",
    label: "Beauty care",
    parent: "Personal care",
    confidence: "low",
    alt: [],
  },
};

/**
 * Obtient le compte PCG suggéré pour un bridgeCategoryId
 */
export function getPCGForBridgeCategory(bridgeCategoryId) {
  const mapping = BRIDGE_TO_PCG[bridgeCategoryId];
  if (!mapping) return null;
  return {
    numero: mapping.pcg,
    intitule: PCG_ACCOUNTS[mapping.pcg] || mapping.pcg,
    confidence: mapping.confidence,
    alternatives: mapping.alt.map((n) => ({
      numero: n,
      intitule: PCG_ACCOUNTS[n] || n,
    })),
  };
}

/**
 * Liste tous les comptes PCG disponibles pour la sélection manuelle
 */
export function getAllPCGAccounts() {
  return Object.entries(PCG_ACCOUNTS)
    .map(([numero, intitule]) => ({ numero, intitule }))
    .sort((a, b) => a.numero.localeCompare(b.numero));
}

/**
 * Retourne le mapping complet sous forme de tableau pour l'onglet Analytique
 */
export function getMappingTableData() {
  return Object.entries(BRIDGE_TO_PCG).map(([id, m]) => ({
    bridgeCategoryId: Number(id),
    bridgeLabel: m.label,
    parentCategory: m.parent,
    pcgNumero: m.pcg,
    pcgIntitule: PCG_ACCOUNTS[m.pcg] || m.pcg,
    confidence: m.confidence,
    alternatives: m.alt.map((n) => ({
      numero: n,
      intitule: PCG_ACCOUNTS[n] || n,
    })),
  }));
}

// Niveaux de confiance avec labels et couleurs
export const CONFIDENCE_CONFIG = {
  high: { label: "Fiable", color: "#22c55e", bgColor: "#dcfce7" },
  medium: { label: "Probable", color: "#f59e0b", bgColor: "#fef3c7" },
  low: { label: "Incertain", color: "#ef4444", bgColor: "#fee2e2" },
};
